name: Cleanup github worker directory
description: Delete (old) files from previous workers.
runs:
  using: 'composite'
  steps:
    - id: cleanup_workspace
      uses: docker://ubuntu:latest
      with:
        args: find /github/workspace/. -name . -o -prune -exec rm -rf -- {} +

    - id: cleanup_home
      uses: docker://ubuntu:latest
      with:
        args: find /github/home/. -name . -o -prune -exec rm -rf -- {} +

    - id: cleanup_node # wtf is it owned by root?!
      uses: docker://ubuntu:latest
      with:
        args: rm -rf /opt/actions-runner/_work/_tool/node
