name: Cleanup github worker directory
description: Delete (old) files from previous workers.
runs:
  using: 'composite'
  steps:
    - id: cleanup
      uses: docker://ubuntu:latest
      with:
        args: find /github/workspace/. -name . -o -prune -exec rm -rf -- {} +
